name: 'WTOP Broadcasting Content Management Pilot' # used in page titles
fedora:
  namespace: avalon
domain:
  host:
  port:
  protocol:
dropbox:
  path: '/apps/bcast/avalon/dropbox/'
  upload_uri:
encoding:
  engine_adapter: matterhorn
matterhorn:
  root: 'http://localhost:8080/'
  baseApplication: 'avalon'
  cleanup_log: 'log/cleanup_jobs.log'
  media_path: '/apps/bcast/avalon/masterfiles/'
mediainfo:
  path: '/usr/bin/mediainfo'
ffmpeg:
  path: '/usr/local/bin/ffmpeg'
email:
  comments:
  notification:
  support:
  mailer:
    smtp:
      address: 'libsmtp.umd.edu'
      port: 587
      enable_starttls_auto: false
streaming:
  server: :generic
  stream_token_ttl: 20 #minutes
  rtmp_base:
  http_base:
  default_quality: 'medium'
  content_path: '/apps/bcast/avalon/rtmp_streams'
groups:
  system_groups: [administrator, group_manager, manager]
master_file_management:
  strategy: 'none' #'delete', or 'move' (for move uncomment and configure next line)
  #path: '/path/to/move/to'
bib_retriever:
  protocol: sru
  url: http://zgate.example.edu:9000/exampledb
  query: rec.id='%s'
controlled_vocabulary:
  path: config/controlled_vocabulary.yml
auth:
  configuration:
    - :name: Avalon Test Auth
      :provider: :identity
      :params:
        :fields:
        - :email